// * Set Actions
export const SET_PROVIDER = "SET_PROVIDER";
export const SET_PROVIDER_MULTIPLE = "SET_PROVIDER_MULTIPLE";
export const SET_PROVIDER_STATUS = "SET_PROVIDER_STATUS";

export const ENABLE_REQUEST = "ENABLE_REQUEST";
export const ENABLE_SUCCESS = "ENABLE_SUCCESS";
export const ENABLE_FAILURE = "ENABLE_FAILURE";

export const INIT_CONTRACT_REQUEST = "INIT_CONTRACT_REQUEST";
export const INIT_CONTRACT_SUCCESS = "INIT_CONTRACT_SUCCESS";
export const INIT_CONTRACT_FAILURE = "INIT_CONTRACT_FAILURE";

export const BALANCE_SET = "BALANCE_SET";
export const ENS_ADDRESS_SET = "ENS_ADDRESS_SET";
export const NETWORK_SET = "NETWORK_SET";
export const NONCE_SET = "NONCE_SET";

/* ----------------------- */
/*         Contact         */
/* ----------------------- */
export const CONTRACT_INITIALIZE_REQUEST = "CONTRACT_INITIALIZE_REQUEST";
export const CONTRACT_INITIALIZE_SUCCESS = "CONTRACT_INITIALIZE_SUCCESS";
export const CONTRACT_INITIALIZE_FAILURE = "CONTRACT_INITIALIZE_FAILURE";

export const SET_ADDRESS = "SET_ADDRESS";
